알림 / Post,QnA 댓글,대댓글,신고,삭제 알림 기능 / 이은철
ToTee-Block/Main pull request #56
Opened 2024-12-18 03:44 UTC by LEEEUNCHEOL96

# Post,QnA 신고 및 삭제 알림
## 신고
- 신고자에게 신고 완료 알림 전송
- 관리자에게 신고 접수 알림 전송

## 삭제
- 작성자에게 관리자에의해 삭제 완료 알림 전송
- 관리자에게 삭제 완료 알림 전송

# Post, QnA 댓글 및 대댓글 알림
- 댓글 : 작성자 에게 알림 전송
- 대댓글 : 부모댓글(댓글작성자) 에게 알림 전송

#참고사항
- #54 기반으로 알림 백앤드 기능 추가

2024-12-18 04:09 UTC, jinainkorea reviewed
저 신고 하는거 ReportController, ReportService 이런 식으로 순수 신고관련 파일들만 사용해서 제거 pr 통과되고 머지되면 그거 보고 다시 하셔야 할 듯 해요🥲

comment관련은 어차피 신고기능 없고, post, qna 게시글만 신고하는데 굳이 나눠야 할 필요를 못 느껴서 targetType으로 구분해놨거든요? 제 pr보시면 도움될 것 같아요

2024-12-18 04:28 UTC, LEEEUNCHEOL96 commented
넵 확인하겠습니다 !

2024-12-18 07:46 UTC, anyeok approved these changes
수고하셨어용 !! 역시 은철님 굳굳입니다 ㅎ 😁

2024-12-18 07:49 UTC, jinainkorea requested changes
수정..!!! 부탁드려요ㅠㅜㅠㅜㅠㅜㅠ

2024-12-18 07:49 UTC, jinainkorea commented on backend/src/main/java/com/example/Main/domain/Post/controller/ApiV1AdminPostController.java
> +
제가 pr했을 때 적어놓은 것들 이해 못 하신거 같아요🥲
여기 추가한 신고자 및 관리자에게 게시물 신고 알림 전송은 ApiV1ReportController에만 추가하시면 됩니다.!
프론트에서 다른 신고컨트롤러는 사용하지 않는걸로 제가 수정했어요ㅜㅜ

아래 메소드 부분에 알림 전송 코드 추가 하시면 될 거 같아요.
혹시 추가로 메소드 이름 'reportPost' => 'report'로 바꿔주시면 감사하겠습니다..!
```
 @PostMapping("/{targetType}/{targetId}")
    public RsData reportPost(@PathVariable("targetType") String targetType,
                                        @PathVariable("targetId") Long targetId,
                                        @Valid @RequestBody ReportRequest reportRequest,
                                        Principal principal) {
```

2024-12-18 08:39 UTC, LEEEUNCHEOL96 commented on backend/src/main/java/com/example/Main/domain/Post/controller/ApiV1AdminPostController.java
> +
아하 제가 이해를 잘못했네요
단순 신고 선택지 출력을 위해 만드신건줄 알았습니다..ㅎㅎ;;

        // 신고자에게 알림 전송
        notificationService.sendNotification(
                String.valueOf(report.getReporter().getId()),
                "신고가 되었습니다."
        );

        // 관리자에게 신고 알림 전송
        notificationService.sendNotificationToAdmins(
                "신고가 되었습니다. 관리자 확인이 필요합니다."
        );

- 알림 확인 

![image](https://github.com/user-attachments/assets/dcd07cb1-bc9e-4e3d-b8cb-1216048f74be)
![image](https://github.com/user-attachments/assets/14728b7c-53ed-4d50-9d32-d188639e8795)



'reportPost' => 'report' 변경 완료

2024-12-19 00:19 UTC, jinainkorea approved these changes
ㅎㅎ무한 피드백 고생하셨어용

2024-12-19 01:43 UTC, merged